/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsdToEtbRouteImport } from './routes/usd-to-etb'
import { Route as TimeInEthiopiaRouteImport } from './routes/time-in-ethiopia'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GoldPriceEthiopiaRouteImport } from './routes/gold-price-ethiopia'
import { Route as EthiopianHolidaysRouteImport } from './routes/ethiopian-holidays'
import { Route as EthiopianDateTodayRouteImport } from './routes/ethiopian-date-today'
import { Route as EthiopianCalendarConverterRouteImport } from './routes/ethiopian-calendar-converter'
import { Route as EthiopianCalendarRouteImport } from './routes/ethiopian-calendar'
import { Route as DateDifferenceRouteImport } from './routes/date-difference'
import { Route as CurrencyConverterRouteImport } from './routes/currency-converter'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgeCalculatorRouteImport } from './routes/age-calculator'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsdToEtbRoute = UsdToEtbRouteImport.update({
  id: '/usd-to-etb',
  path: '/usd-to-etb',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeInEthiopiaRoute = TimeInEthiopiaRouteImport.update({
  id: '/time-in-ethiopia',
  path: '/time-in-ethiopia',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldPriceEthiopiaRoute = GoldPriceEthiopiaRouteImport.update({
  id: '/gold-price-ethiopia',
  path: '/gold-price-ethiopia',
  getParentRoute: () => rootRouteImport,
} as any)
const EthiopianHolidaysRoute = EthiopianHolidaysRouteImport.update({
  id: '/ethiopian-holidays',
  path: '/ethiopian-holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const EthiopianDateTodayRoute = EthiopianDateTodayRouteImport.update({
  id: '/ethiopian-date-today',
  path: '/ethiopian-date-today',
  getParentRoute: () => rootRouteImport,
} as any)
const EthiopianCalendarConverterRoute =
  EthiopianCalendarConverterRouteImport.update({
    id: '/ethiopian-calendar-converter',
    path: '/ethiopian-calendar-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const EthiopianCalendarRoute = EthiopianCalendarRouteImport.update({
  id: '/ethiopian-calendar',
  path: '/ethiopian-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DateDifferenceRoute = DateDifferenceRouteImport.update({
  id: '/date-difference',
  path: '/date-difference',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyConverterRoute = CurrencyConverterRouteImport.update({
  id: '/currency-converter',
  path: '/currency-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeCalculatorRoute = AgeCalculatorRouteImport.update({
  id: '/age-calculator',
  path: '/age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/currency-converter': typeof CurrencyConverterRoute
  '/date-difference': typeof DateDifferenceRoute
  '/ethiopian-calendar': typeof EthiopianCalendarRoute
  '/ethiopian-calendar-converter': typeof EthiopianCalendarConverterRoute
  '/ethiopian-date-today': typeof EthiopianDateTodayRoute
  '/ethiopian-holidays': typeof EthiopianHolidaysRoute
  '/gold-price-ethiopia': typeof GoldPriceEthiopiaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/time-in-ethiopia': typeof TimeInEthiopiaRoute
  '/usd-to-etb': typeof UsdToEtbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/currency-converter': typeof CurrencyConverterRoute
  '/date-difference': typeof DateDifferenceRoute
  '/ethiopian-calendar': typeof EthiopianCalendarRoute
  '/ethiopian-calendar-converter': typeof EthiopianCalendarConverterRoute
  '/ethiopian-date-today': typeof EthiopianDateTodayRoute
  '/ethiopian-holidays': typeof EthiopianHolidaysRoute
  '/gold-price-ethiopia': typeof GoldPriceEthiopiaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/time-in-ethiopia': typeof TimeInEthiopiaRoute
  '/usd-to-etb': typeof UsdToEtbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/age-calculator': typeof AgeCalculatorRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/currency-converter': typeof CurrencyConverterRoute
  '/date-difference': typeof DateDifferenceRoute
  '/ethiopian-calendar': typeof EthiopianCalendarRoute
  '/ethiopian-calendar-converter': typeof EthiopianCalendarConverterRoute
  '/ethiopian-date-today': typeof EthiopianDateTodayRoute
  '/ethiopian-holidays': typeof EthiopianHolidaysRoute
  '/gold-price-ethiopia': typeof GoldPriceEthiopiaRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/time-in-ethiopia': typeof TimeInEthiopiaRoute
  '/usd-to-etb': typeof UsdToEtbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ads.txt'
    | '/age-calculator'
    | '/contact'
    | '/cookies'
    | '/currency-converter'
    | '/date-difference'
    | '/ethiopian-calendar'
    | '/ethiopian-calendar-converter'
    | '/ethiopian-date-today'
    | '/ethiopian-holidays'
    | '/gold-price-ethiopia'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/time-in-ethiopia'
    | '/usd-to-etb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ads.txt'
    | '/age-calculator'
    | '/contact'
    | '/cookies'
    | '/currency-converter'
    | '/date-difference'
    | '/ethiopian-calendar'
    | '/ethiopian-calendar-converter'
    | '/ethiopian-date-today'
    | '/ethiopian-holidays'
    | '/gold-price-ethiopia'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/time-in-ethiopia'
    | '/usd-to-etb'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ads.txt'
    | '/age-calculator'
    | '/contact'
    | '/cookies'
    | '/currency-converter'
    | '/date-difference'
    | '/ethiopian-calendar'
    | '/ethiopian-calendar-converter'
    | '/ethiopian-date-today'
    | '/ethiopian-holidays'
    | '/gold-price-ethiopia'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/time-in-ethiopia'
    | '/usd-to-etb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  AgeCalculatorRoute: typeof AgeCalculatorRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CurrencyConverterRoute: typeof CurrencyConverterRoute
  DateDifferenceRoute: typeof DateDifferenceRoute
  EthiopianCalendarRoute: typeof EthiopianCalendarRoute
  EthiopianCalendarConverterRoute: typeof EthiopianCalendarConverterRoute
  EthiopianDateTodayRoute: typeof EthiopianDateTodayRoute
  EthiopianHolidaysRoute: typeof EthiopianHolidaysRoute
  GoldPriceEthiopiaRoute: typeof GoldPriceEthiopiaRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TimeInEthiopiaRoute: typeof TimeInEthiopiaRoute
  UsdToEtbRoute: typeof UsdToEtbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usd-to-etb': {
      id: '/usd-to-etb'
      path: '/usd-to-etb'
      fullPath: '/usd-to-etb'
      preLoaderRoute: typeof UsdToEtbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-in-ethiopia': {
      id: '/time-in-ethiopia'
      path: '/time-in-ethiopia'
      fullPath: '/time-in-ethiopia'
      preLoaderRoute: typeof TimeInEthiopiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-price-ethiopia': {
      id: '/gold-price-ethiopia'
      path: '/gold-price-ethiopia'
      fullPath: '/gold-price-ethiopia'
      preLoaderRoute: typeof GoldPriceEthiopiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethiopian-holidays': {
      id: '/ethiopian-holidays'
      path: '/ethiopian-holidays'
      fullPath: '/ethiopian-holidays'
      preLoaderRoute: typeof EthiopianHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethiopian-date-today': {
      id: '/ethiopian-date-today'
      path: '/ethiopian-date-today'
      fullPath: '/ethiopian-date-today'
      preLoaderRoute: typeof EthiopianDateTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethiopian-calendar-converter': {
      id: '/ethiopian-calendar-converter'
      path: '/ethiopian-calendar-converter'
      fullPath: '/ethiopian-calendar-converter'
      preLoaderRoute: typeof EthiopianCalendarConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethiopian-calendar': {
      id: '/ethiopian-calendar'
      path: '/ethiopian-calendar'
      fullPath: '/ethiopian-calendar'
      preLoaderRoute: typeof EthiopianCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date-difference': {
      id: '/date-difference'
      path: '/date-difference'
      fullPath: '/date-difference'
      preLoaderRoute: typeof DateDifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-converter': {
      id: '/currency-converter'
      path: '/currency-converter'
      fullPath: '/currency-converter'
      preLoaderRoute: typeof CurrencyConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-calculator': {
      id: '/age-calculator'
      path: '/age-calculator'
      fullPath: '/age-calculator'
      preLoaderRoute: typeof AgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  AgeCalculatorRoute: AgeCalculatorRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CurrencyConverterRoute: CurrencyConverterRoute,
  DateDifferenceRoute: DateDifferenceRoute,
  EthiopianCalendarRoute: EthiopianCalendarRoute,
  EthiopianCalendarConverterRoute: EthiopianCalendarConverterRoute,
  EthiopianDateTodayRoute: EthiopianDateTodayRoute,
  EthiopianHolidaysRoute: EthiopianHolidaysRoute,
  GoldPriceEthiopiaRoute: GoldPriceEthiopiaRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TimeInEthiopiaRoute: TimeInEthiopiaRoute,
  UsdToEtbRoute: UsdToEtbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
